### ISSUE TITLE
Upgrade Log4J2 dependencies version

### ISSUE THREAD

**Issue by leon-qr-li** [anasoid/jmeter-as-code#184]
**Is your feature request related to a problem? Please describe.**
Log4J2 has a security vulnerability for version previous than 2.17.1. Currently, the maven dependencies using 2.16.0.
my workaround is to add the 2.17.1 version dependencies independently in my project. 
https://logging.apache.org/log4j/2.x/

**Describe the solution you'd like**
The dependencies need to updated, the latest version of JMeter already addressed this upgrade but I'm not sure if there's other related JMeter library change that may affect this project. So for now, upgrade the log4j version would be great.

**Describe alternatives you've considered**
Is this possible to attempt use the latest version of JMeter ? how often we plan to upgrade the Jmeter packages on regular basis ?

**Comment by anasoid** [comment]
Hello @leon-qr-li ,

The master branch is already patched by the last version and renovate (https://github.com/renovatebot/renovate) is already enabled, and so the master is always using last libraries.

For vulnerability log4J if you use jmeter-as-code to generate JMX file (it's the preferred way)  than vulnerability is to be taken in consideration in the jmeter used to execute jmx file.

The compatibly for generated JMX file  Is garanted to be executed by any 5.4.x version , and also automated test are executed using jmeter 5.5-snapshot (https://github.com/anasoid/jmeter-as-code/actions/workflows/snapshot.yml) to early check with future version

Even i don't think there is a risk to generate jmx file with log4j 2.16 I will release tomorow a patched version with all  updated library from master.

**Comment by leon-qr-li** [comment]
Great, good to know ! Thanks @anasoid

**Comment by anasoid** [comment]
new version V0.6.4 is released with all new  libraries versions

https://s01.oss.sonatype.org/content/groups/public/org/anasoid/jmc/jmc-core/v0.6.4/

it will take some hours to be on all maven mirrors
